### ISSUE TITLE
hello.sh doesn't work on Windows

### ISSUE THREAD

**Issue by dciobanu** [vioricaciobanu/exercises_shell#1]
Hi!

When running `./hello.sh` in `bash` on MS Windows I'm seeing:
```sh
$ ./hello.sh
hello
```
The variable $USER isn't set.  Instead, on Windows $USERNAME is used. Would be cool if the script can check either one.

**Comment by vioricaciobanu** [comment]
https://github.com/vioricaciobanu/exercises_shell/pull/2

**Comment by vioricaciobanu** [comment]
Issue solved
